version: '3.9'

services:
  frontend:
    build:
      context: ./pizzashop
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: pizzashop-app
    ports:
      - 8082:80
    restart: unless-stopped
